### ISSUE TITLE
Picker jump three by three on wasmjs

### ISSUE THREAD

**Issue by N7ghtm4r3** [darkokoa/datetime-wheel-picker#42]
Hi, I am using the library on a `KMP` application which has also the `wasmjs` target, and the picker on the `web` platform when selecting with mouse scrolling a date part, that value jump from that part to three values after. This from happens for all the tested date parts such `days`, `months`, `years`, `hours `and `minutes`. For example from `January` to `April` month value with just one mouse scroll. Following there is the my code snippet:
```kotlin
WheelDateTimePicker(
    modifier = Modifier
        .padding(
            vertical = 16.dp
        )
        .align(Alignment.CenterHorizontally),
    rowCount = 5
) { snappedDateTime -> 
    // use the value picked
}
```

**Comment by darkokoa** [comment]
Thank you for reporting this issue! I've successfully reproduced the problem you described, and can confirm it exists on both JS and WASM targets.

This is quite an interesting case - I noticed that the value-jumping behavior (e.g. January → April) only occurs when using the mouse wheel to scroll. When using a touchpad or touch-screen gestures to scroll through the picker, the values increment/decrement normally one step at a time.

I've also checked the behavior on Desktop (JVM), and interestingly, the same mouse wheel scrolling works correctly there without any jumping issues.

I suspect this might be specifically related to the CMP implementation on web platforms (though I need to investigate further to be certain). I'll need some time to investigate the root cause of this behavior.

**Comment by N7ghtm4r3** [comment]
Hi, you are welcome! Yes I made the same tests you said to be sure about the issue and actually seems like the issue is related to `wasmjs` or `js` implementation. I am approaching in these days on `wasmjs` and has strange behavior sometimes!

**Comment by darkokoa** [comment]
Good news! The mouse scrolling issue you reported has been fixed in Compose 1.8.
Please upgrade to:

**Comment by N7ghtm4r3** [comment]
Hi, thank you for the info and for the time you spent on it! I am happy to see this fix

**Comment by toasterofbread** [comment]
Hate to be the bearer of bad news but it seems like Compose 1.8 doesn't actually fix this. The [release notes for Compose v1.8.0-alpha04](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.8.0-alpha04) mention that the version of the material3 dependency was downgraded from 1.4.0 to 1.3.1, and I'm pretty sure this bug is caused by a regression in material3 1.4.0.

When I tried to use version 1.1.0-alpha03-compose1.8 of this library I got runtime failures because I was overriding the version of material3 to 1.4.0 in my project (as suggested in the build notes), creating a mismatch between it and the library. I cloned the library and set the material3 version to 1.4.0, built locally, and it now worked in my project but the issue with the scroll wheel on Wasm still remains.

You should also be able to observe this by trying the library with Compose v1.9.0-alpha02 (which brings the material3 version back up to 1.4.0), as the bug is still present, at least for me.

**Comment by toasterofbread** [comment]
I'm still experiencing this issue with version 1.1.0-alpha03-compose1.8, both in my own project and when running the sample project on Firefox and Chromium. It jumps an inconsistent amount of items though, usually 6 or 7. Same behaviour when I update the library's Compose version to 1.9.0-alpha02.

Initially I thought this was an issue with the material3 library version, but that turned out to be irrelevant (I commented about this earlier and deleted it when I realised).

**Comment by darkokoa** [comment]
Thanks for the valuable feedback! 

I just retested this myself. Long story short, here are my results: both CMP 1.7 and 1.8 scroll correctly on Firefox, but exhibit the jumping behavior on Chrome. I'm using a Logitech G502 for testing.

I sincerely apologize for my earlier claim that this was resolved - I must have been testing on a different browser at the time, which led to the confusion.

I'll investigate further and look for possible solutions.

**Comment by darkokoa** [comment]
Seems like JB is planning to fix the web platform scroll issues: https://youtrack.jetbrains.com/issue/CMP-7168/Web.-Adapt-scroll-physics-to-the-OS
